function [car_cell] = parameters_loop(cP,aP,eP,DTp,Bp,tP)

% output car_cell: a cell containing a car for each possible combination of parameters

    [mass,driver_weight,accel_driver_weight,wheelbase,weight_dist,track_width,wheel_radius,cg_height,...
    roll_center_height_front,roll_center_height_rear,R_sf,I_zz,cda,cla,distribution,cla_p_deg_p,D_p_deg_p,...
    accel_cda,accel_cla,acc_cla_p_deg_p,acc_D_p_deg_p,redline,shift_point,shift_time,final_drive,drivetrain_efficiency,...
    G_d1,G_d2_overrun,G_d2_driving,brake_distribution,max_braking_torque,...
    gamma_f,gamma_r,p_i,ackermann,camber_compliance_f,camber_compliance_r,static_r_toe,...
    grip_scaling_front,grip_scaling_rear,I_wheel,I_driveline,Crr] = ndgrid(...
    cP.mass,cP.driver_weight,cP.accel_driver_weight,cP.wheelbase,cP.weight_dist,cP.track_width,...
    cP.wheel_radius,cP.cg_height,cP.roll_center_height_front,cP.roll_center_height_rear,...
    cP.R_sf,cP.I_zz,aP.cda,aP.cla,aP.distribution,aP.cla_p_deg_p,aP.D_p_deg_p,aP.accel_cda,aP.accel_cla,aP.acc_cla_p_deg_p,aP.acc_D_p_deg_p,eP.redline,...
    eP.shift_point,eP.shift_time,DTp.final_drive,DTp.drivetrain_efficiency,...
    DTp.G_d1,DTp.G_d2_overrun,DTp.G_d2_driving,Bp.brake_distribution,Bp.max_braking_torque,...
    tP.gamma_f,tP.gamma_r,tP.p_i,cP.ackermann,cP.camber_compliance_f,cP.camber_compliance_r,cP.static_r_toe,...
    tP.grip_scaling_front,tP.grip_scaling_rear,cP.I_wheel,cP.I_driveline,cP.Crr);
% NOTE: the output list above and this input list must stay in EXACTLY the
% same order. They are matched positionally, so inserting a parameter in one
% and not the other silently rotates every value after it onto the wrong
% variable -- that is how aero distribution once ended up reading cda. New
% parameters go on the END of both lists.

for i = 1:numel(mass)
    aero = Aero(cda(i), cla(i), distribution(i), cla_p_deg_p(i),D_p_deg_p(i));
    aero_accel = Aero(accel_cda(i), accel_cla(i), distribution(i), acc_cla_p_deg_p(i),acc_D_p_deg_p(i));  % Use same distribution unless there's a separate accel_distribution

    powertrain = Powertrain(redline(i), shift_point(i), eP.gears, eP.primary_reduction, eP.torque_fn, shift_time(i), ...
        final_drive(i), wheel_radius(i), drivetrain_efficiency(i), ...
        G_d1(i), G_d2_overrun(i), G_d2_driving(i), brake_distribution(i), max_braking_torque(i));

    tire = Tire2(p_i(i), tP.Fx_parameters, tP.Fy_parameters, tP.friction_scaling_factor);

    % Same grip scaling on the accel car: it is the same tyres on the same
    % surface, only a different wing.
    car = Car(mass(i)+driver_weight(i), wheelbase(i), weight_dist(i), track_width(i), wheel_radius(i), ...
        cg_height(i), roll_center_height_front(i), roll_center_height_rear(i), R_sf(i), I_zz(i), ...
        gamma_f(i),gamma_r(i), camber_compliance_f(i), camber_compliance_r(i), aero, powertrain, tire, ackermann(i), static_r_toe(i), ...
        grip_scaling_front(i), grip_scaling_rear(i), I_wheel(i), I_driveline(i), Crr(i));

    accel_car = Car(mass(i)+accel_driver_weight(i), wheelbase(i), weight_dist(i), track_width(i), wheel_radius(i), ...
        cg_height(i), roll_center_height_front(i), roll_center_height_rear(i), R_sf(i), I_zz(i), ...
        gamma_f(i),gamma_r(i), camber_compliance_f(i),camber_compliance_r(i), aero_accel, powertrain, tire, ackermann(i), static_r_toe(i), ...
        grip_scaling_front(i), grip_scaling_rear(i), I_wheel(i), I_driveline(i), Crr(i));

    car_cell{i,1} = car;
    car_cell{i,2} = accel_car;
end
